### ISSUE TITLE
CSS: Search settings text is same color as background

### ISSUE THREAD

**Issue by gitrust** [seanwcom/Red-Graphite-for-Obsidian#31] opened 2023-10-23 06:07 UTC
Issue:

The color of text for the search settings toggle dialog is the same as background color. Therefore description for toggles are not visible.

Expected:

The foreground color for text is adapted to theme style.

Theme Version is 1.0.1

**Comment by ALonelySheep** [comment] 2024-06-01 21:31
Possible duplicate of #29 

One possible (temporary) fix is to create a CSS snippet and copy the paste the code below into it:
```
/* for coloring the colon and text before it, as well as the search box title */
.suggestion-container .suggestion-item {
    /* color: var(--nav-item-color); */
    color: var(--text-muted);
}

/* for coloring text after the colon */
.suggestion-container .search-suggest-info-text {
    color: var(--text-muted);
}
```

**Comment by seanwcom** [comment] 2024-10-30 18:16
I've just gone thru and implemented many fixes, this is now corrected in the latest release.

**Closed by seanwcom** 2024-10-30 18:16 UTC
